[platformio]
src_dir = .

[env:esp01]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.0.0
    thingpulse/ESP8266 Weather Station@^2.0.0
    squix78/JsonStreamingParser@^1.0.0
