#!/usr/bin/env python3
# /// script
# requires-python = ">=3.8"
# dependencies = ["platformio"]
# ///
"""Setup script for weatherstation-ch.
Prompts for config, generates config.h, optionally builds/uploads via PlatformIO.

Usage:
  uv run setup.py           # config + build (installs platformio automatically)
  uv run setup.py --config  # config only, no build
"""

import argparse
import glob
import os
import socket
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, "config.h")

DEFAULTS = {
    "WIFI_SSID": "",
    "WIFI_PWD": "",
    "OWM_API_KEY": "",
    "OWM_LOCATION_ID": "2660161",
}


def read_existing_config():
    """Parse current config.h values if it exists."""
    values = dict(DEFAULTS)
    if not os.path.exists(CONFIG_FILE):
        return values
    with open(CONFIG_FILE) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#define"):
                parts = line.split(None, 2)
                if len(parts) == 3 and parts[1] in values:
                    values[parts[1]] = parts[2].strip('"')
    return values


def prompt_config():
    """Prompt user for configuration values."""
    current = read_existing_config()
    values = {}

    print("\n--- Weatherstation CH Setup ---\n")

    for key, label, secret in [
        ("WIFI_SSID", "WiFi SSID", False),
        ("WIFI_PWD", "WiFi password", True),
        ("OWM_API_KEY", "OpenWeatherMap API key (https://docs.thingpulse.com/how-tos/openweathermap-key/)", True),
        ("OWM_LOCATION_ID", "Location ID (https://openweathermap.org/find?q=)", False),
    ]:
        default = current.get(key, DEFAULTS.get(key, ""))
        display_default = default
        if secret and default:
            display_default = default[:4] + "..." + default[-4:] if len(default) > 8 else "****"

        if default:
            raw = input(f"  {label} [{display_default}]: ").strip()
            values[key] = raw if raw else default
        else:
            while True:
                raw = input(f"  {label}: ").strip()
                if raw:
                    values[key] = raw
                    break
                print("    (required)")

    return values


def write_config(values):
    """Write config.h from values dict."""
    with open(CONFIG_FILE, "w") as f:
        f.write("// Auto-generated by setup.py — do not commit this file\n")
        f.write("#ifndef CONFIG_H\n")
        f.write("#define CONFIG_H\n\n")
        for key in ["WIFI_SSID", "WIFI_PWD", "OWM_API_KEY", "OWM_LOCATION_ID"]:
            f.write(f'#define {key:<16s}"{values[key]}"\n')
        f.write("\n#endif\n")
    print("\n  config.h written.")


OTA_HOST = "weatherclock.local"


def detect_port():
    """Try to find the ESP01 serial port."""
    ports = glob.glob("/dev/ttyUSB*") + glob.glob("/dev/ttyACM*")
    return ports[0] if ports else None


def detect_ota():
    """Check if the device is reachable via mDNS for OTA upload."""
    try:
        ip = socket.getaddrinfo(OTA_HOST, 8266, socket.AF_INET)[0][4][0]
        return ip
    except (socket.gaierror, OSError):
        return None


def build_and_upload():
    """Build and optionally upload with PlatformIO."""
    print("\n  Compiling...")
    result = subprocess.run(["pio", "run"], cwd=SCRIPT_DIR)
    if result.returncode != 0:
        print("  Build failed.")
        return

    print("  Build OK!\n")

    # Detect available upload methods
    ota_ip = detect_ota()
    usb_port = detect_port()

    options = []
    if ota_ip:
        options.append(("ota", ota_ip))
        print(f"  [OTA] Found {OTA_HOST} at {ota_ip}")
    if usb_port:
        options.append(("usb", usb_port))
        print(f"  [USB] Found device at {usb_port}")

    if not options:
        print("  No device found — neither OTA nor USB.")
        print(f"  For OTA: make sure {OTA_HOST} is on your network.")
        print("  For USB: connect the ESP01 via USB adapter.")
        return

    # If both available, let user choose
    if len(options) == 1:
        method, target = options[0]
    else:
        print()
        for i, (method, target) in enumerate(options, 1):
            label = "OTA (wireless)" if method == "ota" else "USB (serial)"
            print(f"  {i}) {label} — {target}")
        print(f"  {len(options) + 1}) Skip upload")

        choice = input(f"\n  Upload method [1]: ").strip()
        if choice == str(len(options) + 1):
            return
        idx = int(choice) - 1 if choice.isdigit() and 0 < int(choice) <= len(options) else 0
        method, target = options[idx]

    if method == "ota":
        confirm = input(f"\n  Upload OTA to {OTA_HOST} ({target})? [Y/n]: ").strip().lower()
        if confirm not in ("", "y", "yes"):
            return
        print(f"  Uploading OTA to {target}...")
        subprocess.run(
            ["pio", "run", "-e", "esp01_ota", "-t", "upload", "--upload-port", target],
            cwd=SCRIPT_DIR,
        )
    else:
        confirm = input(f"\n  Upload via USB to {target}? [Y/n]: ").strip().lower()
        if confirm not in ("", "y", "yes"):
            return
        print(f"  Uploading to {target}...")
        subprocess.run(
            ["pio", "run", "-t", "upload", "--upload-port", target],
            cwd=SCRIPT_DIR,
        )


def main():
    parser = argparse.ArgumentParser(description="Weatherstation CH setup")
    parser.add_argument("--config", action="store_true", help="Only generate config.h, skip build")
    args = parser.parse_args()

    values = prompt_config()
    write_config(values)

    if args.config:
        print("\n  Done! (config only)")
        return

    print("\n--- Build Options ---")
    print("  1) PlatformIO (recommended, handles all dependencies)")
    print("  2) Arduino IDE (manual library install)")
    print("  3) Skip build")

    choice = input("\n  Choice [1]: ").strip()

    if choice in ("", "1"):
        build_and_upload()

    elif choice == "2":
        print("\n  Arduino IDE instructions:")
        print("  1. Board: Generic ESP8266 Module (1M flash)")
        print("  2. Install libraries via Library Manager:")
        print("     - ESP8266 Weather Station (ThingPulse)")
        print("     - ESP8266 and ESP32 OLED driver for SSD1306 displays")
        print("     - Json Streaming Parser")
        print("  3. Open weatherstation-ch.ino")
        print("  4. Compile & Upload")

    print("\n  Done!")


if __name__ == "__main__":
    main()
